### ISSUE TITLE
Dissapearing items 2 electric boogaloo

### ISSUE THREAD

**Issue by Lanthanid** [Dibeo/DDD-Dungeons-Dragons-Dimensions#2]
Yep, its me, im back, heres the setup. the fan wasnt even blowing and it left, i was trying to turn iron into steel bc samuri dynasty lets you blast it that way, it worked and then left after the fan stopped

![2024-12-07_10 52 08](https://github.com/user-attachments/assets/51a48e09-499c-4eb8-8cb4-b52d4257487b)

**Comment by Dibeo** [comment]
You said it was fixed is it still the case ? if yes close the issue or notify me so i can close it.

**Comment by Lanthanid** [comment]
it acted fixed then it started doin it as soon as i build the above

**Comment by Dibeo** [comment]
After trying, it seems it does not work, and it's a problem that come from mod, sadly I can't fix this, but I try using a depot and that work, so if you could try this and tell me if it fixes your problems.

**Comment by Lanthanid** [comment]
Yea i found the depot trick,works well its just a tad annoying that entity persistence doesn't work well, i modded it with a time extension mod and it didn't fix it

**Comment by Dibeo** [comment]
If you think the issue is fixed please close it.

If you didn't close it or didn't ask anything else in 48 hours, I will close it.

Hope you have a good time playing DDD : D
